"use client";

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/models/69a46c3a6e4b038c0e322ff6.glb -o src/components/Avatar.tsx -k -r public
*/

import { useAnimations, useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import { button, useControls } from "leva";
import { useEffect, useRef, useState } from "react";
import * as THREE from "three";
import { useChat } from "@/hooks/useChat";
import type { Group, SkinnedMesh, Material, Bone } from "three";
import type { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Hips: Bone;
    Wolf3D_Body: SkinnedMesh;
    Wolf3D_Outfit_Bottom: SkinnedMesh;
    Wolf3D_Outfit_Footwear: SkinnedMesh;
    Wolf3D_Outfit_Top: SkinnedMesh;
    Wolf3D_Hair: SkinnedMesh;
    EyeLeft: SkinnedMesh;
    EyeRight: SkinnedMesh;
    Wolf3D_Head: SkinnedMesh;
    Wolf3D_Teeth: SkinnedMesh;
  };
  materials: {
    Wolf3D_Body: Material;
    Wolf3D_Outfit_Bottom: Material;
    Wolf3D_Outfit_Footwear: Material;
    Wolf3D_Outfit_Top: Material;
    Wolf3D_Hair: Material;
    Wolf3D_Eye: Material;
    Wolf3D_Skin: Material;
    Wolf3D_Teeth: Material;
  };
};

interface FacialExpression {
  [key: string]: number;
}

interface FacialExpressions {
  [key: string]: FacialExpression;
}

const facialExpressions: FacialExpressions = {
  default: {},

  smile: {
    mouthSmileLeft: 0.6,
    mouthSmileRight: 0.6,
    cheekSquintLeft: 0.4,
    cheekSquintRight: 0.4,
    eyeSquintLeft: 0.3,
    eyeSquintRight: 0.3,
  },

  bigSmile: {
    mouthSmileLeft: 1,
    mouthSmileRight: 1,
    cheekSquintLeft: 0.8,
    cheekSquintRight: 0.8,
    eyeSquintLeft: 0.5,
    eyeSquintRight: 0.5,
    browInnerUp: 0.3,
  },

  sad: {
    mouthFrownLeft: 1,
    mouthFrownRight: 1,
    browInnerUp: 0.6,
    eyeLookDownLeft: 0.4,
    eyeLookDownRight: 0.4,
    mouthShrugLower: 0.5,
  },

  crying: {
    mouthFrownLeft: 1,
    mouthFrownRight: 1,
    browInnerUp: 0.9,
    eyeSquintLeft: 0.7,
    eyeSquintRight: 0.7,
    mouthOpen: 0.3,
  },

  angry: {
    browDownLeft: 1,
    browDownRight: 1,
    eyeSquintLeft: 0.8,
    eyeSquintRight: 0.8,
    noseSneerLeft: 0.7,
    noseSneerRight: 0.7,
    mouthPressLeft: 0.8,
    mouthPressRight: 0.8,
  },

  annoyed: {
    browDownLeft: 0.6,
    browDownRight: 0.6,
    mouthPressLeft: 0.6,
    mouthPressRight: 0.6,
    eyeSquintLeft: 0.4,
    eyeSquintRight: 0.4,
  },

  surprised: {
    eyeWideLeft: 1,
    eyeWideRight: 1,
    jawOpen: 0.6,
    browInnerUp: 1,
  },

  shocked: {
    eyeWideLeft: 1,
    eyeWideRight: 1,
    jawOpen: 1,
    mouthFunnel: 0.8,
    browInnerUp: 1,
  },

  confused: {
    browInnerUp: 0.7,
    browDownLeft: 0.4,
    eyeSquintLeft: 0.3,
    mouthLeft: 0.4,
  },

  thinking: {
    browInnerUp: 0.5,
    eyeLookUpLeft: 0.5,
    eyeLookUpRight: 0.5,
    mouthPressLeft: 0.4,
    mouthPressRight: 0.4,
  },

  skeptical: {
    browDownLeft: 0.6,
    browInnerUp: 0.4,
    mouthRight: 0.5,
  },

  happy: {
    mouthSmileLeft: 0.8,
    mouthSmileRight: 0.8,
    cheekSquintLeft: 0.6,
    cheekSquintRight: 0.6,
  },

  laughing: {
    mouthSmileLeft: 1,
    mouthSmileRight: 1,
    jawOpen: 0.6,
    eyeSquintLeft: 0.8,
    eyeSquintRight: 0.8,
    cheekSquintLeft: 0.9,
    cheekSquintRight: 0.9,
  },

  wink: {
    eyeBlinkLeft: 1,
    mouthSmileLeft: 0.4,
    mouthSmileRight: 0.4,
  },

  playful: {
    mouthSmileLeft: 0.6,
    mouthSmileRight: 0.3,
    browInnerUp: 0.3,
    eyeSquintLeft: 0.3,
  },

  kiss: {
    mouthPucker: 1,
    eyeSquintLeft: 0.2,
    eyeSquintRight: 0.2,
  },

  disgust: {
    noseSneerLeft: 1,
    noseSneerRight: 1,
    mouthUpperUpLeft: 0.5,
    mouthUpperUpRight: 0.5,
  },

  sleepy: {
    eyeBlinkLeft: 0.7,
    eyeBlinkRight: 0.7,
    jawOpen: 0.2,
  },

  bored: {
    eyeLookDownLeft: 0.4,
    eyeLookDownRight: 0.4,
    mouthPressLeft: 0.3,
    mouthPressRight: 0.3,
  },

  crazy: {
    browInnerUp: 0.9,
    eyeLookInLeft: 1,
    eyeLookInRight: 1,
    jawOpen: 0.8,
    tongueOut: 1,
  },

  funnyFace: {
    jawLeft: 0.6,
    mouthPucker: 0.5,
    cheekPuff: 1,
    noseSneerLeft: 1,
    noseSneerRight: 0.5,
  },
};

const corresponding: { [key: string]: string } = {
  A: "viseme_PP",
  B: "viseme_kk",
  C: "viseme_I",
  D: "viseme_AA",
  E: "viseme_O",
  F: "viseme_U",
  G: "viseme_FF",
  H: "viseme_TH",
  X: "viseme_PP",
};

let setupMode = false;

interface AvatarProps {
  [key: string]: any;
}

export function Avatar(props: AvatarProps) {
  const { nodes, materials, scene } = useGLTF(
    "/models/models2.glb",
  ) as unknown as GLTFResult & { scene: Group };

  const { message, onMessagePlayed, chat } = useChat();
  const [lipsync, setLipsync] = useState<any>();
  const [audio, setAudio] = useState<HTMLAudioElement | null>(null);
  const [blink, setBlink] = useState(false);
  const [winkLeft, setWinkLeft] = useState(false);
  const [winkRight, setWinkRight] = useState(false);
  const [facialExpression, setFacialExpression] = useState("");
  const [animation, setAnimation] = useState("");
  const [audioStartTime, setAudioStartTime] = useState<number>(0);

  // Create persistent audio ref to fix autoplay policy issues
  const audioRef = useRef<HTMLAudioElement | null>(null);

  const { animations } = useGLTF("/models/animations.glb");
  const group = useRef<Group>(null);
  const { actions, mixer } = useAnimations(animations, group);

  useEffect(() => {
    const initialAnimation = animations.find((a) => a.name === "Idle")
      ? "Idle"
      : animations[0]?.name || "";
    setAnimation(initialAnimation);
  }, [animations]);

  // Initialize persistent audio ref to fix autoplay policy issues
  useEffect(() => {
    audioRef.current = new Audio();
    audioRef.current.preload = "auto";
    audioRef.current.crossOrigin = "anonymous"; // Fix CORS issues

    audioRef.current.onended = () => {
      console.log("Audio playback ended");
      setAudioStartTime(0);
      onMessagePlayed();
    };

    return () => {
      audioRef.current?.pause();
      audioRef.current = null;
    };
  }, []);

  useEffect(() => {
    if (!message) {
      setAnimation("Idle");
      setAudio(null);
      setAudioStartTime(0);
      return;
    }
    setAnimation(message.animation);
    setFacialExpression(message.facialExpression);
    setLipsync(message.lipsync);

    // Play audio if available, otherwise use browser speech synthesis
    if (message.audio && audioRef.current) {
      const audio = audioRef.current;

      console.log(
        "Playing Cartesia audio:",
        message.audio.substring(0, 50) + "...",
      );
      console.log("Audio data URL length:", message.audio.length);
      console.log(
        "Audio data URL starts with:",
        message.audio.substring(0, 20),
      );

      // Add more detailed error handling
      audio.onerror = (error) => {
        console.error("Audio playback error:", error);
        console.error("Audio src:", audio.src);
        console.error("Audio networkState:", audio.networkState);
        console.error("Audio readyState:", audio.readyState);
        console.error("Audio error details:", audio.error);

        // Fallback to browser speech synthesis if audio fails
        if (message.text && window.speechSynthesis) {
          console.log("Falling back to browser speech synthesis");
          const utterance = new SpeechSynthesisUtterance(message.text);
          utterance.rate = 1.0;
          utterance.pitch = 1.0;
          utterance.volume = 1.0;
          utterance.onend = () => {
            setAudioStartTime(0);
            onMessagePlayed();
          };
          window.speechSynthesis.speak(utterance);
        }
      };

      audio.oncanplay = () => {
        console.log("Audio can play, starting playback...");
      };

      audio.onloadedmetadata = () => {
        console.log("Audio metadata loaded, duration:", audio.duration);
      };

      audio.oncanplaythrough = () => {
        console.log("Audio can play through, starting playback...");
      };

      audio.onwaiting = () => {
        console.log("Audio waiting for data...");
      };

      audio.onstalled = () => {
        console.log("Audio stalled...");
      };

      audio.onabort = () => {
        console.log("Audio playback aborted");
      };

      audio.onsuspend = () => {
        console.log("Audio playback suspended");
      };

      audio.onemptied = () => {
        console.log("Audio playback emptied");
      };

      audio.onloadeddata = () => {
        console.log("Audio data loaded");
      };

      audio.src = message.audio;
      setAudioStartTime(performance.now() / 1000); // Convert to seconds
      setAudio(audio);

      // Try to play with better error handling
      const playPromise = audio.play();

      if (playPromise !== undefined) {
        playPromise
          .then(() => {
            console.log("Audio playback started successfully");
          })
          .catch((err) => {
            console.error("Audio playback failed:", err);
            console.error("Error name:", err.name);
            console.error("Error message:", err.message);
            console.error("Audio element readyState:", audio.readyState);
            console.error("Audio element networkState:", audio.networkState);

            // Fallback to browser speech synthesis if audio fails
            if (message.text && window.speechSynthesis) {
              console.log("Falling back to browser speech synthesis");
              const utterance = new SpeechSynthesisUtterance(message.text);
              utterance.rate = 1.0;
              utterance.pitch = 1.0;
              utterance.volume = 1.0;
              utterance.onend = () => {
                setAudioStartTime(0);
                onMessagePlayed();
              };
              window.speechSynthesis.speak(utterance);
            }
          });
      } else {
        console.log("Audio playback not supported, using fallback");
        if (message.text && window.speechSynthesis) {
          const utterance = new SpeechSynthesisUtterance(message.text);
          utterance.rate = 1.0;
          utterance.pitch = 1.0;
          utterance.volume = 1.0;
          utterance.onend = () => {
            setAudioStartTime(0);
            onMessagePlayed();
          };
          window.speechSynthesis.speak(utterance);
        }
      }
    } else if (message.text && window.speechSynthesis) {
      console.log(
        "Using browser speech synthesis fallback (no Cartesia audio)",
      );
      // Fallback to browser speech synthesis
      // Still use lipsync data even without audio
      setAudioStartTime(performance.now() / 1000); // Convert to seconds
      const utterance = new SpeechSynthesisUtterance(message.text);
      utterance.rate = 1.0;
      utterance.pitch = 1.0;
      utterance.volume = 1.0;
      utterance.onend = () => {
        setAudioStartTime(0);
        onMessagePlayed();
      };
      window.speechSynthesis.speak(utterance);
    } else {
      // No audio available, still animate with lipsync for estimated duration
      console.log("No audio available, using estimated duration");
      setAudioStartTime(performance.now() / 1000);
      const duration = (message.text?.split(" ").length || 10) * 400; // ~400ms per word
      setTimeout(() => {
        setAudioStartTime(0);
        onMessagePlayed();
      }, duration);
    }
  }, [message, onMessagePlayed]);

  useEffect(() => {
    if (!animation || !actions[animation]) return;

    actions[animation]
      .reset()
      .fadeIn(mixer.stats.actions.inUse === 0 ? 0 : 0.5)
      .play();
    return () => {
      actions[animation]?.fadeOut(0.5);
    };
  }, [animation, actions, mixer]);

  const lerpMorphTarget = (target: string, value: number, speed = 0.1) => {
    scene.traverse((child) => {
      if (child instanceof THREE.SkinnedMesh && child.morphTargetDictionary) {
        const index = child.morphTargetDictionary[target];
        if (
          index === undefined ||
          child.morphTargetInfluences?.[index] === undefined
        ) {
          return;
        }
        child.morphTargetInfluences[index] = THREE.MathUtils.lerp(
          child.morphTargetInfluences[index],
          value,
          speed,
        );

        if (!setupMode) {
          try {
            set({
              [target]: value,
            });
          } catch (e) {
            // Silently catch errors when leva is not in setup mode
          }
        }
      }
    });
  };

  useFrame(() => {
    if (!setupMode && nodes.EyeLeft.morphTargetDictionary) {
      Object.keys(nodes.EyeLeft.morphTargetDictionary).forEach((key) => {
        const mapping = facialExpressions[facialExpression];
        if (key === "eyeBlinkLeft" || key === "eyeBlinkRight") {
          return; // eyes wink/blink are handled separately
        }
        if (mapping && mapping[key]) {
          lerpMorphTarget(key, mapping[key], 0.1);
        } else {
          lerpMorphTarget(key, 0, 0.1);
        }
      });
    }

    lerpMorphTarget("eyeBlinkLeft", blink || winkLeft ? 1 : 0, 0.5);
    lerpMorphTarget("eyeBlinkRight", blink || winkRight ? 1 : 0, 0.5);

    // LIPSYNC
    if (setupMode) {
      return;
    }

    const appliedMorphTargets: string[] = [];
    if (message && lipsync && audioStartTime > 0) {
      // Calculate current time based on audio or performance timer
      const currentAudioTime = audio
        ? audio.currentTime
        : performance.now() / 1000 - audioStartTime;

      // Apply lipsync morphs
      for (let i = 0; i < lipsync.mouthCues.length; i++) {
        const mouthCue = lipsync.mouthCues[i];
        if (
          currentAudioTime >= mouthCue.start &&
          currentAudioTime <= mouthCue.end
        ) {
          appliedMorphTargets.push(corresponding[mouthCue.value]);
          lerpMorphTarget(corresponding[mouthCue.value], 1, 0.2);
          break;
        }
      }
    }

    Object.values(corresponding).forEach((value) => {
      if (appliedMorphTargets.includes(value)) {
        return;
      }
      lerpMorphTarget(value, 0, 0.1);
    });
  });

  const [, set] = useControls("MorphTarget", () =>
    Object.assign(
      {},
      ...Object.keys(nodes.EyeLeft.morphTargetDictionary || {}).map((key) => {
        return {
          [key]: {
            label: key,
            value: 0,
            min:
              nodes.EyeLeft.morphTargetInfluences?.[
                nodes.EyeLeft.morphTargetDictionary?.[key] || 0
              ] || 0,
            max: 1,
            onChange: (val: number) => {
              if (setupMode) {
                lerpMorphTarget(key, val, 1);
              }
            },
          },
        };
      }),
    ),
  );

  useControls("FacialExpressions", {
    chat: button(() => chat("")),
    winkLeft: button(() => {
      setWinkLeft(true);
      setTimeout(() => setWinkLeft(false), 300);
    }),
    winkRight: button(() => {
      setWinkRight(true);
      setTimeout(() => setWinkRight(false), 300);
    }),
    animation: {
      value: animation,
      options: animations.map((a) => a.name),
      onChange: (value: string) => setAnimation(value),
    },
    facialExpression: {
      options: Object.keys(facialExpressions),
      onChange: (value: string) => setFacialExpression(value),
    },
    enableSetupMode: button(() => {
      setupMode = true;
    }),
    disableSetupMode: button(() => {
      setupMode = false;
    }),
    logMorphTargetValues: button(() => {
      const emotionValues: { [key: string]: number } = {};
      Object.keys(nodes.EyeLeft.morphTargetDictionary || {}).forEach((key) => {
        if (key === "eyeBlinkLeft" || key === "eyeBlinkRight") {
          return; // eyes wink/blink are handled separately
        }
        const value =
          nodes.EyeLeft.morphTargetInfluences?.[
            nodes.EyeLeft.morphTargetDictionary?.[key] || 0
          ];
        if (value && value > 0.01) {
          emotionValues[key] = value;
        }
      });
      console.log(JSON.stringify(emotionValues, null, 2));
    }),
  });

  useEffect(() => {
    let blinkTimeout: NodeJS.Timeout;
    const nextBlink = () => {
      blinkTimeout = setTimeout(
        () => {
          setBlink(true);
          setTimeout(() => {
            setBlink(false);
            nextBlink();
          }, 200);
        },
        THREE.MathUtils.randInt(1000, 5000),
      );
    };
    nextBlink();
    return () => clearTimeout(blinkTimeout);
  }, []);

  return (
    <group {...props} dispose={null} ref={group}>
      <primitive object={nodes.Hips} />
      <primitive object={nodes.Hips} />
      <skinnedMesh
        name="EyeLeft"
        geometry={nodes.EyeLeft.geometry as any}
        material={materials.Wolf3D_Eye as any}
        skeleton={nodes.EyeLeft.skeleton as any}
        morphTargetDictionary={nodes.EyeLeft.morphTargetDictionary}
        morphTargetInfluences={nodes.EyeLeft.morphTargetInfluences}
      />
      <skinnedMesh
        name="EyeRight"
        geometry={nodes.EyeRight.geometry as any}
        material={materials.Wolf3D_Eye as any}
        skeleton={nodes.EyeRight.skeleton as any}
        morphTargetDictionary={nodes.EyeRight.morphTargetDictionary}
        morphTargetInfluences={nodes.EyeRight.morphTargetInfluences}
      />
      <skinnedMesh
        name="Wolf3D_Head"
        geometry={nodes.Wolf3D_Head.geometry as any}
        material={materials.Wolf3D_Skin as any}
        skeleton={nodes.Wolf3D_Head.skeleton as any}
        morphTargetDictionary={nodes.Wolf3D_Head.morphTargetDictionary}
        morphTargetInfluences={nodes.Wolf3D_Head.morphTargetInfluences}
      />
      <skinnedMesh
        name="Wolf3D_Teeth"
        geometry={nodes.Wolf3D_Teeth.geometry as any}
        material={materials.Wolf3D_Teeth as any}
        skeleton={nodes.Wolf3D_Teeth.skeleton as any}
        morphTargetDictionary={nodes.Wolf3D_Teeth.morphTargetDictionary}
        morphTargetInfluences={nodes.Wolf3D_Teeth.morphTargetInfluences}
      />
      <skinnedMesh
        geometry={nodes.Wolf3D_Hair.geometry as any}
        material={materials.Wolf3D_Hair as any}
        skeleton={nodes.Wolf3D_Hair.skeleton as any}
      />
      <skinnedMesh
        geometry={nodes.Wolf3D_Body.geometry as any}
        material={materials.Wolf3D_Body as any}
        skeleton={nodes.Wolf3D_Body.skeleton as any}
      />
      <skinnedMesh
        geometry={nodes.Wolf3D_Outfit_Bottom.geometry as any}
        material={materials.Wolf3D_Outfit_Bottom as any}
        skeleton={nodes.Wolf3D_Outfit_Bottom.skeleton as any}
      />
      <skinnedMesh
        geometry={nodes.Wolf3D_Outfit_Footwear.geometry as any}
        material={materials.Wolf3D_Outfit_Footwear as any}
        skeleton={nodes.Wolf3D_Outfit_Footwear.skeleton as any}
      />
      <skinnedMesh
        geometry={nodes.Wolf3D_Outfit_Top.geometry as any}
        material={materials.Wolf3D_Outfit_Top as any}
        skeleton={nodes.Wolf3D_Outfit_Top.skeleton as any}
      />
    </group>
  );
}

useGLTF.preload("/models/models2.glb");
useGLTF.preload("/models/animations.glb");
